spring.application.name=ferreteria

#Configuration for the database connection posgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/ferreteria
spring.datasource.username=ferreteria
spring.datasource.password=ferreteria

#Logging configuration
logging.level.org.springframework=INFO

