spring.application.name=ferreteria

#Configuration for the database connection posgresql
spring.datasource.url=jdbc:postgresql://localhost:6432/ferreteria
spring.datasource.username=ferreteria_app
spring.datasource.password=ferreteriaApp

#Logging configuration
logging.level.org.springframework=INFO

